### ISSUE TITLE
Is it possible for me to use this app using my own api

### ISSUE THREAD

**Issue by karcshub** [openshopio/openshop.io-android#22]
Am trying out this app and am wondering if i can use my web api (for an ecommerce website) in this app.My api is developed on .net technology and am trying to find a way pf consuming it using this app.Any help and advise is welcome.Thanks

**Comment by ZelvaJan** [comment]
You have two options. Firstly, in Apiary you will find endpoints that you must implement on your server. Second, you will modify the android application in order to process your api, which basically means to modify data models (and their mapping to displayed values) in android application to match your api.
