### ISSUE TITLE
How to connect to woocommerce?

### ISSUE THREAD

**Issue by jpxgen** [openshopio/openshop.io-android#24]
Can you please explain is it possible to use this app took connect to woocommerce backbend system?

**Comment by ZelvaJan** [comment]
It is possible to connect it almost to every type of server. But it will require some work. You have basicaly two options:
1) On your server you will implement all the endpoints from documentation in Apiary (here: http://docs.bfeshopapiconnector.apiary.io/#). Then in android app you just chagne hostname and some other small changes and it should work.
2) Second, you will modify the android application in order to process your current api, which basically means to modify data models (and their mapping to displayed values) in android application to match your api.
