### ISSUE TITLE
Is possible to connect to any backend php?

### ISSUE THREAD

**Issue by Jsaiao** [openshopio/openshop.io-android#25]
Amazing work. ;)

**Comment by n-92** [comment]
I wanted to post the same question.

**Comment by ZelvaJan** [comment]
Thanks. It is possible. You have two options: 
1) On your server you will implement all the endpoints from documentation  in Apiary (here: http://docs.bfeshopapiconnector.apiary.io/#). Then in android app you just chagne hostname and some other small changes and it should work. 
2) Second, you will modify the android application in order to process your current api, which basically means to modify data models (and their mapping to displayed values) in android application to match your api.

**Comment by Jsaiao** [comment]
Thanks for your help.
