### ISSUE TITLE
Dynamic Product Attributes

### ISSUE THREAD

**Issue by amirhkf** [openshopio/openshop.io-android#26]
There is just two ( color and size ) attributes for products . It will be problem with products with another attributes like core , ram and etc. . Is there any solution for this limitation ?

**Comment by ZelvaJan** [comment]
Sorry for a late response. 
It's possible, but it requires your work to design new attributes into the app and also enlarge the data models with these new values. Good news is that product filtering is dynamic, so it requires only a small change in the server code, in order to filter the products with new attributes.
