### ISSUE TITLE
Error while building on AndroidStudio

### ISSUE THREAD

**Issue by aurifae** [openshopio/openshop.io-android#36]
I get the following error after import, while building the gradle

Error:(21, 1) A problem occurred evaluating project ':app'.
> You should define KEYSTORE_PASSWORD, KEYSTORE_ALIAS and KEY_PASSWORD in gradle.properties.groovy.lang.MissingPropertyException: Could not get unknown property 'KEYSTORE_PASSWORD' for SigningConfig_Decorated{name=release, storeFile=C:\Users\n007AX\Desktop\OpenShop\trunk\app\openshopKeystore.jks, storePassword=null, keyAlias=null, keyPassword=null, storeType=C:\Users\n007AX\Desktop\OpenShop\trunk\app\openshopKeystore.jks, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.

Could you please help me fix this ?

**Comment by rhonyabdullah** [comment]
This probably can be fixed by your self.
Open this file [gradle.properties](https://github.com/openshopio/openshop.io-android/blob/master/gradle.properties) from your project, and add this line to the bottom:
`KEYSTORE_PASSWORD="your_keystore_password"`
`KEYSTORE_ALIAS="your_keystore_alias"`
`KEY_PASSWORD="your_key_password"`

remember, once you upload the apk into the playstore with this "related keystore" you can't change it anymore otherwise your project will not showing any update notification on the playstore while pushing new apk, so pay attention.

Hope it helps.

**Comment by vlchz** [comment]
The error still pops up. I put it under the "org.gradle.jvmargs = -Xmx5120m" code, which is in the gradle.properties file. Am I suppose to do something more than just click save after adding the code?

**Comment by vlchz** [comment]
I figured out the error thanks
