### ISSUE TITLE
Services are not working for open source android app

### ISSUE THREAD

**Issue by vamsich** [openshopio/openshop.io-android#47]
I have configured your open source into my android IDE. Services are not working. I am not getting any data from your services.

I would need those services until I am ready with my own servers.

Please help me on this.

Regards,
Vamsi.

**Comment by sam43** [comment]
I also need the  Updated project which is already on the google play. This repo is not properly working, api base url is always enters to the exception.error message. Any help?

**Comment by ZelvaJan** [comment]
We have problem with our server hosting, so server is sometimes down. The application now works normally. Do you still have this problem?

**Comment by basitanwer** [comment]
The first URL fails
http://77.93.198.186/v1.2/21/navigation_drawer

**Comment by ZelvaJan** [comment]
Fixed now

**Comment by basitanwer** [comment]
Umm link not working again.

**Comment by basitanwer** [comment]
Can you please upload the expected JSONs because every now and then your mocking server API goes down. I need it because as per my understanding this application doesn't follow the REST API as shown here
http://docs.bfeshopapiconnector.apiary.io/#introduction/product-xml-feed 

And your server is right now down again.

**Comment by friendimran** [comment]
yes usually its down
